// export interface Projects {
//   id: number,
// state: string,
// city: string,
// customer: string,
// project_id: string,
// job_count: number,
// progress: number,
// days_aged: number,
// due_date: string,
// current_stage: string
// }

// export const projectsTable = [
// 	{
// 		id: 1,
// 		state: "WI",
// 		city: "West Jordan",
// 		customer: "Frontier",
// 		project_id: "GS243274",
// 		job_count: 2861510,
// 		progress: 29,
// 		days_aged: 5,
// 		due_date: "2022-06-18",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 2,
// 		state: "IN",
// 		city: "New Haven",
// 		customer: "Charter",
// 		project_id: "PP835479",
// 		job_count: 6059832,
// 		progress: 97,
// 		days_aged: 10,
// 		due_date: "2022-11-07",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 3,
// 		state: "LA",
// 		city: "Pittsburgh",
// 		customer: "Charter",
// 		project_id: "QR612286",
// 		job_count: 8277769,
// 		progress: 86,
// 		days_aged: 1,
// 		due_date: "2022-06-05",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 4,
// 		state: "DE",
// 		city: "Bear",
// 		customer: "Frontier",
// 		project_id: "UX985299",
// 		job_count: 4375057,
// 		progress: 43,
// 		days_aged: 3,
// 		due_date: "2022-05-25",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 5,
// 		state: "NV",
// 		city: "Lowell",
// 		customer: "Lumen",
// 		project_id: "PN748974",
// 		job_count: 6857498,
// 		progress: 13,
// 		days_aged: 8,
// 		due_date: "2022-09-29",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 6,
// 		state: "DE",
// 		city: "West Jordan",
// 		customer: "Lumen",
// 		project_id: "CV882646",
// 		job_count: 3777058,
// 		progress: 5,
// 		days_aged: 10,
// 		due_date: "2022-11-25",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 7,
// 		state: "WY",
// 		city: "Colorado Springs",
// 		customer: "Frontier",
// 		project_id: "UC568655",
// 		job_count: 9788419,
// 		progress: 25,
// 		days_aged: 10,
// 		due_date: "2022-08-09",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 8,
// 		state: "AR",
// 		city: "Meridian",
// 		customer: "Charter",
// 		project_id: "RI120887",
// 		job_count: 1144717,
// 		progress: 21,
// 		days_aged: 2,
// 		due_date: "2022-09-17",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 9,
// 		state: "ME",
// 		city: "Gillette",
// 		customer: "Lumen",
// 		project_id: "RP466978",
// 		job_count: 1948981,
// 		progress: 55,
// 		days_aged: 7,
// 		due_date: "2022-07-20",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 10,
// 		state: "MO",
// 		city: "Honolulu",
// 		customer: "Lumen",
// 		project_id: "XP811113",
// 		job_count: 1551311,
// 		progress: 30,
// 		days_aged: 11,
// 		due_date: "2022-03-25",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 11,
// 		state: "MS",
// 		city: "Cambridge",
// 		customer: "Comcast",
// 		project_id: "KZ476485",
// 		job_count: 4100503,
// 		progress: 80,
// 		days_aged: 11,
// 		due_date: "2022-11-29",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 12,
// 		state: "LA",
// 		city: "Las Vegas",
// 		customer: "Charter",
// 		project_id: "SD710191",
// 		job_count: 3051184,
// 		progress: 29,
// 		days_aged: 0,
// 		due_date: "2022-10-07",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 13,
// 		state: "IA",
// 		city: "Essex",
// 		customer: "Lumen",
// 		project_id: "YR321027",
// 		job_count: 3023671,
// 		progress: 33,
// 		days_aged: 9,
// 		due_date: "2022-11-27",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 14,
// 		state: "MD",
// 		city: "Columbia",
// 		customer: "Altice",
// 		project_id: "QR766417",
// 		job_count: 1550339,
// 		progress: 55,
// 		days_aged: 4,
// 		due_date: "2022-05-05",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 15,
// 		state: "TX",
// 		city: "Hillsboro",
// 		customer: "Comcast",
// 		project_id: "QJ733226",
// 		job_count: 2215957,
// 		progress: 54,
// 		days_aged: 6,
// 		due_date: "2022-08-02",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 16,
// 		state: "WY",
// 		city: "Augusta",
// 		customer: "Altice",
// 		project_id: "HO983548",
// 		job_count: 1499651,
// 		progress: 48,
// 		days_aged: 8,
// 		due_date: "2022-03-29",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 17,
// 		state: "WA",
// 		city: "Tampa",
// 		customer: "Charter",
// 		project_id: "FK349383",
// 		job_count: 7781602,
// 		progress: 54,
// 		days_aged: 2,
// 		due_date: "2022-09-15",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 18,
// 		state: "AK",
// 		city: "Tuscaloosa",
// 		customer: "Comcast",
// 		project_id: "US535584",
// 		job_count: 9979325,
// 		progress: 16,
// 		days_aged: 6,
// 		due_date: "2023-01-22",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 19,
// 		state: "FL",
// 		city: "Southaven",
// 		customer: "Comcast",
// 		project_id: "JG185742",
// 		job_count: 1832816,
// 		progress: 47,
// 		days_aged: 3,
// 		due_date: "2022-12-12",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 20,
// 		state: "AZ",
// 		city: "Meridian",
// 		customer: "Altice",
// 		project_id: "WJ502562",
// 		job_count: 6537321,
// 		progress: 8,
// 		days_aged: 4,
// 		due_date: "2022-09-25",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 21,
// 		state: "MA",
// 		city: "Hattiesburg",
// 		customer: "Frontier",
// 		project_id: "FD019417",
// 		job_count: 1574529,
// 		progress: 87,
// 		days_aged: 5,
// 		due_date: "2022-06-21",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 22,
// 		state: "NE",
// 		city: "Frankfort",
// 		customer: "Frontier",
// 		project_id: "UX442163",
// 		job_count: 7806163,
// 		progress: 89,
// 		days_aged: 9,
// 		due_date: "2022-08-03",
// 		current_stage: "Engineering"
// 	},
// 	{
// 		id: 23,
// 		state: "MI",
// 		city: "Cincinnati",
// 		customer: "Lumen",
// 		project_id: "ZC438083",
// 		job_count: 5383873,
// 		progress: 18,
// 		days_aged: 9,
// 		due_date: "2022-07-21",
// 		current_stage: "Construction"
// 	},
// 	{
// 		id: 24,
// 		state: "WY",
// 		city: "Cheyenne",
// 		customer: "Lumen",
// 		project_id: "FY313668",
// 		job_count: 8463347,
// 		progress: 63,
// 		days_aged: 8,
// 		due_date: "2022-08-01",
// 		current_stage: "Construction"
// 	}
// ];